package KieRule;

import com.example.rulesenginepoc.model.RoutingLogicBaseArgs;

global com.example.rulesenginepoc.model.UnitOfWorkDecider unitOfWorkDecider;

dialect  "mvel"

rule "EMR1"
    when
        RoutingLogicBaseArgs(operation == 'read' || cdoId == '1' || resource == 'ExplanationOfBenefit');
    then
        unitOfWorkDecider.setOperationId("bc808772-53e0-11ed-bdc3-0242ac120002");
        unitOfWorkDecider.setConfigType("Patient Access");
        unitOfWorkDecider.setOrchestratorUuid("0ef15c4e-699d-4b0b-a61b-bfc2a9373aa3");
end

rule "EMR2"
    when
        RoutingLogicBaseArgs(operation == 'create' && cdoId == '2' && resource == 'Organization');
    then
        unitOfWorkDecider.setOperationId("b7dc3615-9c05-47c8-9bc2-810afdceadb2");
        unitOfWorkDecider.setConfigType("Public Directory");
        unitOfWorkDecider.setOrchestratorUuid("3c998a97-cfe2-49db-b232-a2a444c2c527");
end

rule "EMR3"
    when
        RoutingLogicBaseArgs(operation == 'search' && cdoId == '3' && resource == 'Organization');
    then
        unitOfWorkDecider.setOperationId("f0991ddd-540d-4300-9084-674d61bb0bce");
        unitOfWorkDecider.setConfigType("Private Application");
        unitOfWorkDecider.setOrchestratorUuid("c96a2b4b-25f4-4b84-94e4-97dacd762358");
end